{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "21735b72-eec8-4285-b0c2-a80152e313b2",
   "metadata": {},
   "outputs": [],
   "source": [
    "import warnings\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from tabulate import tabulate\n",
    "from sklearn.model_selection import train_test_split, GridSearchCV\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "6b32afec-1254-4fb2-a4e1-6b79ce5e878f",
   "metadata": {},
   "outputs": [],
   "source": [
    "warnings.filterwarnings(\"ignore\", category=UserWarning)\n",
    " \n",
    "DOUBLE_LINE = \"=\" * 60\n",
    " \n",
    "FEATURE_LABELS = {\n",
    "    \"Pregnancies\": \"Number of pregnancies\",\n",
    "    \"Glucose\": \"Glucose level (mg/dL)\",\n",
    "    \"BloodPressure\": \"Diastolic blood pressure (mmHg)\",\n",
    "    \"SkinThickness\": \"Skin thickness (mm)\",\n",
    "    \"Insulin\": \"Insulin level (mu U/ml)\",\n",
    "    \"BMI\": \"Body Mass Index (BMI)\",\n",
    "    \"DiabetesPedigreeFunction\": \"Diabetes Pedigree Function (e.g. 0.5)\",\n",
    "    \"Age\": \"Age (years)\",\n",
    "}\n",
    " \n",
    " \n",
    "def print_header(title):\n",
    "    print(\"\\n\" + DOUBLE_LINE)\n",
    "    print(title)\n",
    "    print(DOUBLE_LINE)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "51475c80-4afd-45c7-8633-d8cfa26b353f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================\n",
    "# Part 1: Train the model\n",
    "# ============================================\n",
    "def train_model(csv_path=\"diabetes.csv\"):\n",
    "    \"\"\"Load data, preprocess it, train a KNN model, and print evaluation metrics.\"\"\"\n",
    " \n",
    "    print_header(\"STEP 1: LOADING & PREPROCESSING DATA\")\n",
    "    df = pd.read_csv(csv_path)\n",
    "    print(f\"Dataset loaded successfully -> {df.shape[0]} rows, {df.shape[1]} columns\")\n",
    " \n",
    "    # These features cannot biologically be 0, so treat 0 as a missing value\n",
    "    cols_with_invalid_zero = [\"Glucose\", \"BloodPressure\", \"SkinThickness\", \"Insulin\", \"BMI\"]\n",
    "    df[cols_with_invalid_zero] = df[cols_with_invalid_zero].replace(0, np.nan)\n",
    "    df.fillna(df.median(numeric_only=True), inplace=True)\n",
    "    print(\"Missing values handled (zeros replaced with median values)\")\n",
    " \n",
    "    # Separate features (X) and target variable (y)\n",
    "    X = df.drop(\"Outcome\", axis=1)\n",
    "    y = df[\"Outcome\"]\n",
    "    feature_names = X.columns.tolist()\n",
    " \n",
    "    # Train-test split (stratified to keep class ratio balanced)\n",
    "    X_train, X_test, y_train, y_test = train_test_split(\n",
    "        X, y, test_size=0.2, random_state=42, stratify=y\n",
    "    )\n",
    " \n",
    "    # Feature scaling (critical for KNN since it relies on distance)\n",
    "    scaler = StandardScaler()\n",
    "    scaler.fit(X_train)\n",
    "    X_train_scaled = scaler.transform(X_train)\n",
    "    X_test_scaled = scaler.transform(X_test)\n",
    "    print(\"Feature scaling applied (StandardScaler)\")\n",
    " \n",
    "    print_header(\"STEP 2: TRAINING THE KNN MODEL\")\n",
    "    print(\"Searching for the best K value (testing K = 1 to 30)...\")\n",
    "    param_grid = {\"n_neighbors\": range(1, 31)}\n",
    "    grid = GridSearchCV(KNeighborsClassifier(), param_grid, cv=5, scoring=\"accuracy\")\n",
    "    grid.fit(X_train_scaled, y_train)\n",
    "    best_k = grid.best_params_[\"n_neighbors\"]\n",
    "    print(f\"Best K value found: {best_k}\")\n",
    " \n",
    "    model = KNeighborsClassifier(n_neighbors=best_k)\n",
    "    model.fit(X_train_scaled, y_train)\n",
    "    print(\"Final model trained successfully\")\n",
    " \n",
    "    # Evaluate the model on the test set\n",
    "    y_pred = model.predict(X_test_scaled)\n",
    " \n",
    "    print_header(\"STEP 3: MODEL PERFORMANCE ON TEST SET\")\n",
    " \n",
    "    # --- Metrics table ---\n",
    "    metrics_table = [\n",
    "        [\"Accuracy\", f\"{accuracy_score(y_test, y_pred):.4f}\"],\n",
    "        [\"Precision\", f\"{precision_score(y_test, y_pred):.4f}\"],\n",
    "        [\"Recall\", f\"{recall_score(y_test, y_pred):.4f}\"],\n",
    "        [\"F1 Score\", f\"{f1_score(y_test, y_pred):.4f}\"],\n",
    "    ]\n",
    "    print(\"\\nOverall Metrics:\")\n",
    "    print(tabulate(metrics_table, headers=[\"Metric\", \"Score\"], tablefmt=\"fancy_grid\"))\n",
    " \n",
    "    # --- Confusion matrix table ---\n",
    "    cm = confusion_matrix(y_test, y_pred)\n",
    "    cm_table = [\n",
    "        [\"Actual: No Diabetes\", cm[0][0], cm[0][1]],\n",
    "        [\"Actual: Diabetes\", cm[1][0], cm[1][1]],\n",
    "    ]\n",
    "    print(\"\\nConfusion Matrix:\")\n",
    "    print(tabulate(\n",
    "        cm_table,\n",
    "        headers=[\"\", \"Predicted: No Diabetes\", \"Predicted: Diabetes\"],\n",
    "        tablefmt=\"fancy_grid\"\n",
    "    ))\n",
    " \n",
    "    # --- Classification report table ---\n",
    "    report_dict = classification_report(y_test, y_pred, output_dict=True)\n",
    "    report_table = []\n",
    "    for label in [\"0\", \"1\"]:\n",
    "        row = report_dict[label]\n",
    "        class_name = \"No Diabetes (0)\" if label == \"0\" else \"Diabetes (1)\"\n",
    "        report_table.append([\n",
    "            class_name,\n",
    "            f\"{row['precision']:.2f}\",\n",
    "            f\"{row['recall']:.2f}\",\n",
    "            f\"{row['f1-score']:.2f}\",\n",
    "            int(row['support']),\n",
    "        ])\n",
    "    report_table.append([\n",
    "        \"Weighted Avg\",\n",
    "        f\"{report_dict['weighted avg']['precision']:.2f}\",\n",
    "        f\"{report_dict['weighted avg']['recall']:.2f}\",\n",
    "        f\"{report_dict['weighted avg']['f1-score']:.2f}\",\n",
    "        int(report_dict['weighted avg']['support']),\n",
    "    ])\n",
    "    print(\"\\nClassification Report:\")\n",
    "    print(tabulate(\n",
    "        report_table,\n",
    "        headers=[\"Class\", \"Precision\", \"Recall\", \"F1-Score\", \"Support\"],\n",
    "        tablefmt=\"fancy_grid\"\n",
    "    ))\n",
    "    print(DOUBLE_LINE)\n",
    " \n",
    "    return model, scaler, feature_names"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "86bf12f6-7dff-4fa9-a015-57e7a91e516e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================\n",
    "# Part 2: Get user input\n",
    "# ============================================\n",
    "def get_user_input(feature_names):\n",
    "    \"\"\"Prompt the user to enter their health details.\"\"\"\n",
    " \n",
    "    print_header(\"ENTER PATIENT DETAILS\")\n",
    " \n",
    "    user_data = []\n",
    "    for feature in feature_names:\n",
    "        label = FEATURE_LABELS.get(feature, feature)\n",
    "        while True:\n",
    "            try:\n",
    "                value = float(input(f\"{label:<45}: \"))\n",
    "                user_data.append(value)\n",
    "                break\n",
    "            except ValueError:\n",
    "                print(\"  -> Invalid input, please enter a number.\")\n",
    " \n",
    "    return pd.DataFrame([user_data], columns=feature_names)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "798a324d-bf34-4f8a-9a1e-4bc5bb75691d",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================\n",
    "# Part 3: Prediction\n",
    "# ============================================\n",
    "def predict_diabetes(model, scaler, user_input_df):\n",
    "    \"\"\"Scale the user's input and predict whether they are diabetic.\"\"\"\n",
    " \n",
    "    user_input_scaled = scaler.transform(user_input_df)\n",
    "    prediction = model.predict(user_input_scaled)[0]\n",
    "    probability = model.predict_proba(user_input_scaled)[0]\n",
    " \n",
    "    print_header(\"PREDICTION RESULT\")\n",
    " \n",
    "    result_text = \"HIGH likelihood of diabetes\" if prediction == 1 else \"LOW likelihood of diabetes\"\n",
    " \n",
    "    result_table = [\n",
    "        [\"Prediction\", result_text],\n",
    "        [\"Probability of Diabetes\", f\"{probability[1] * 100:.2f}%\"],\n",
    "        [\"Probability of No Diabetes\", f\"{probability[0] * 100:.2f}%\"],\n",
    "    ]\n",
    "    print(tabulate(result_table, tablefmt=\"fancy_grid\"))\n",
    " \n",
    "    print(\"\\nNote: For academic purposes only. This is NOT a medical\")\n",
    "    print(\"diagnosis. Please consult a doctor for any concerns.\")\n",
    "    print(DOUBLE_LINE)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "f9bf0eb5-b876-4bc1-8eb8-4c73dbe0c404",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "============================================================\n",
      "STEP 1: LOADING & PREPROCESSING DATA\n",
      "============================================================\n",
      "Dataset loaded successfully -> 768 rows, 9 columns\n",
      "Missing values handled (zeros replaced with median values)\n",
      "Feature scaling applied (StandardScaler)\n",
      "\n",
      "============================================================\n",
      "STEP 2: TRAINING THE KNN MODEL\n",
      "============================================================\n",
      "Searching for the best K value (testing K = 1 to 30)...\n",
      "Best K value found: 20\n",
      "Final model trained successfully\n",
      "\n",
      "============================================================\n",
      "STEP 3: MODEL PERFORMANCE ON TEST SET\n",
      "============================================================\n",
      "\n",
      "Overall Metrics:\n",
      "╒═══════════╤═════════╕\n",
      "│ Metric    │   Score │\n",
      "╞═══════════╪═════════╡\n",
      "│ Accuracy  │  0.7597 │\n",
      "├───────────┼─────────┤\n",
      "│ Precision │  0.6977 │\n",
      "├───────────┼─────────┤\n",
      "│ Recall    │  0.5556 │\n",
      "├───────────┼─────────┤\n",
      "│ F1 Score  │  0.6186 │\n",
      "╘═══════════╧═════════╛\n",
      "\n",
      "Confusion Matrix:\n",
      "╒═════════════════════╤══════════════════════════╤═══════════════════════╕\n",
      "│                     │   Predicted: No Diabetes │   Predicted: Diabetes │\n",
      "╞═════════════════════╪══════════════════════════╪═══════════════════════╡\n",
      "│ Actual: No Diabetes │                       87 │                    13 │\n",
      "├─────────────────────┼──────────────────────────┼───────────────────────┤\n",
      "│ Actual: Diabetes    │                       24 │                    30 │\n",
      "╘═════════════════════╧══════════════════════════╧═══════════════════════╛\n",
      "\n",
      "Classification Report:\n",
      "╒═════════════════╤═════════════╤══════════╤════════════╤═══════════╕\n",
      "│ Class           │   Precision │   Recall │   F1-Score │   Support │\n",
      "╞═════════════════╪═════════════╪══════════╪════════════╪═══════════╡\n",
      "│ No Diabetes (0) │        0.78 │     0.87 │       0.82 │       100 │\n",
      "├─────────────────┼─────────────┼──────────┼────────────┼───────────┤\n",
      "│ Diabetes (1)    │        0.7  │     0.56 │       0.62 │        54 │\n",
      "├─────────────────┼─────────────┼──────────┼────────────┼───────────┤\n",
      "│ Weighted Avg    │        0.75 │     0.76 │       0.75 │       154 │\n",
      "╘═════════════════╧═════════════╧══════════╧════════════╧═══════════╛\n",
      "============================================================\n",
      "\n",
      "============================================================\n",
      "ENTER PATIENT DETAILS\n",
      "============================================================\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Number of pregnancies                        :  2\n",
      "Glucose level (mg/dL)                        :  9\n",
      "Diastolic blood pressure (mmHg)              :  140\n",
      "Skin thickness (mm)                          :  8\n",
      "Insulin level (mu U/ml)                      :  3\n",
      "Body Mass Index (BMI)                        :  30\n",
      "Diabetes Pedigree Function (e.g. 0.5)        :  0.5\n",
      "Age (years)                                  :  34\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "============================================================\n",
      "PREDICTION RESULT\n",
      "============================================================\n",
      "╒════════════════════════════╤════════════════════════════╕\n",
      "│ Prediction                 │ LOW likelihood of diabetes │\n",
      "├────────────────────────────┼────────────────────────────┤\n",
      "│ Probability of Diabetes    │ 10.00%                     │\n",
      "├────────────────────────────┼────────────────────────────┤\n",
      "│ Probability of No Diabetes │ 90.00%                     │\n",
      "╘════════════════════════════╧════════════════════════════╛\n",
      "\n",
      "Note: For academic purposes only. This is NOT a medical\n",
      "diagnosis. Please consult a doctor for any concerns.\n",
      "============================================================\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "\n",
      "Predict again? (y/n):  y\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "============================================================\n",
      "ENTER PATIENT DETAILS\n",
      "============================================================\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Number of pregnancies                        :  0\n",
      "Glucose level (mg/dL)                        :  12\n",
      "Diastolic blood pressure (mmHg)              :  135\n",
      "Skin thickness (mm)                          :  \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  -> Invalid input, please enter a number.\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Skin thickness (mm)                          :  23\n",
      "Insulin level (mu U/ml)                      :  12\n",
      "Body Mass Index (BMI)                        :  30\n",
      "Diabetes Pedigree Function (e.g. 0.5)        :  0.5\n",
      "Age (years)                                  :  22\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "============================================================\n",
      "PREDICTION RESULT\n",
      "============================================================\n",
      "╒════════════════════════════╤════════════════════════════╕\n",
      "│ Prediction                 │ LOW likelihood of diabetes │\n",
      "├────────────────────────────┼────────────────────────────┤\n",
      "│ Probability of Diabetes    │ 5.00%                      │\n",
      "├────────────────────────────┼────────────────────────────┤\n",
      "│ Probability of No Diabetes │ 95.00%                     │\n",
      "╘════════════════════════════╧════════════════════════════╛\n",
      "\n",
      "Note: For academic purposes only. This is NOT a medical\n",
      "diagnosis. Please consult a doctor for any concerns.\n",
      "============================================================\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "\n",
      "Predict again? (y/n):  n\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Program ended. Thank you for using the system!\n"
     ]
    }
   ],
   "source": [
    "# ============================================\n",
    "# Main Program\n",
    "# ============================================\n",
    "def main():\n",
    "    model, scaler, feature_names = train_model(\"diabetes.csv\")\n",
    " \n",
    "    while True:\n",
    "        user_input_df = get_user_input(feature_names)\n",
    "        predict_diabetes(model, scaler, user_input_df)\n",
    " \n",
    "        again = input(\"\\nDo you want to Predict again? (y/n): \").strip().lower()\n",
    "        if again != \"y\":\n",
    "            print(\"\\nThank you for using the system!\")\n",
    "            break\n",
    " \n",
    " \n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ca5708f2-9dd2-491f-8e9e-6c30a1eb80de",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e8446ee3-1ad5-4cd3-88c3-e16eabda1490",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
